CREATE PROCEDURE spUpisSlogKalkUI
(

	@inAkcija		AS CHAR(3),
	@inStanicaUnosa	AS CHAR(5),
	@inOtpUprava		AS CHAR(4),
	@inOtpStanica		AS CHAR(7),
	@inOtpBroj		AS INTEGER,
	@inOtpDatum		AS DATETIME,
	@inObrGodina		AS CHAR(4),
	@inObrMesec		AS CHAR(2),
	@inZsUlPrelaz 		AS CHAR(5),
	@inUlEtiketa 		AS INTEGER,
	@inDatumUlaza		AS DATETIME,
	@inZsIzPrelaz 		AS CHAR(5),
	@inIzEtiketa		AS INTEGER,
	@inDatumIzlaza		AS DATETIME,
	@inPrUprava	 	AS CHAR(4),
	@inPrStanica		AS CHAR(7),
	@inPrBroj		AS INTEGER,
	@inPrDatum		AS DATETIME,
	@inBrojVoza		AS INTEGER,
	@inSatVoza	 	AS CHAR(5),
	@inNajava	 	AS CHAR(10),
	@inNajavaKola		AS INTEGER,
	@inNajava2	 	AS CHAR(10),
	@inNajavaKola2	AS INTEGER,
	@inSifraTarife		AS CHAR(2),
	@inUgovor		AS CHAR(6),
	@inPosiljalac		AS INTEGER,
	@inPlatilacFRR		AS INTEGER,
	@inPrimalac		AS INTEGER,
	@inPlatilacNFR		AS INTEGER,
	@inVrPos		AS CHAR(1),
	@inPrevoz		AS CHAR(1),
	@inSaobracaj		AS CHAR(1),
	@inVrSao		AS INTEGER,
	@inVrPrevoza		AS CHAR(1),
	@inUKK		AS INTEGER,
	@inZsPrevozniPut	AS INTEGER,
	@intkm			AS INTEGER,
	@inskm			AS INTEGER,
	@inIzjava		AS INTEGER,
	@inFrRacun		AS CHAR(10),
	@inK115_e		AS DECIMAL(12,2),
	@inK115_d		AS DECIMAL(12,2),
	@inFrankoPoCIM_e	AS DECIMAL(12,2),
	@inFrankoPoCIM_d	AS DECIMAL(12,2),
	@inFrNaknade		AS CHAR(8),
   	@inFrDoPrelaza		AS CHAR(4),
	@inIncoterms		AS CHAR(3),
	@inIsporukaVal		AS CHAR(3),
	@inIsporuka		AS DECIMAL(12,2),
	@inPouzeceVal		AS CHAR(3),
	@inPouzece		AS DECIMAL(12,2),
	@inVrednostRobeVal	AS CHAR(3),
	@inVrednostRobe	AS DECIMAL(12,2),
	@inTLValuta		AS CHAR(2),
	@inTLSumaFR		AS DECIMAL(12,2),
	@inTLSumaUP		AS DECIMAL(12,2),
	@inTLSumaFRDin	AS DECIMAL(12,2),
	@inTLSumaUPDin	AS DECIMAL(12,2),
	@inTLPrevFR		AS DECIMAL(12,2),
	@inTLPrevUP		AS DECIMAL(12,2),
	@inTLNakFR		AS DECIMAL(12,2),
	@inTLNakUP		AS DECIMAL(12,2),
	@inTLPrevFRDin	AS DECIMAL(12,2),
	@inTLPrevUPDin	AS DECIMAL(12,2),
	@inTLNakFRDin	AS DECIMAL(12,2),
	@inTLNakUPDin	AS DECIMAL(12,2),
	@inTLNakCo82		AS DECIMAL(12,2),
	@inTLNakCo		AS DECIMAL(12,2),
	@inrSumaFR		AS DECIMAL(12,2),
	@inrSumaUP		AS DECIMAL(12,2),
	@inrSumaFRDin		AS DECIMAL(12,2),
	@inrSumaUPDin	AS DECIMAL(12,2),
	@inrK115_d		AS DECIMAL(12,2),
	@inSifraK211		AS CHAR(20),
	@inReferent1		AS CHAR(4),
	@inObradaDatum	AS DATETIME,
	@inCarStanica		AS CHAR(5),
	@inCarPrimalacPIB	AS CHAR(10),
	@inCarPrimalacNaziv	AS CHAR(30),
	@inCarPrimalacSediste	AS CHAR(30),
	@inCarPrimalacZemlja	AS CHAR(5),
	@inCarValuta		AS CHAR(5),
	@inCarFaktura		AS DECIMAL(12,2),
	@inCarBrFakture	AS CHAR(10),
	@inCarDokumenti	AS CHAR(100),
	@inCarKnjiga		AS CHAR(10),
	@inCarDatum		AS DATETIME,
	@inCarAgent 	    	AS CHAR(30),
	@inCarXml        		AS CHAR(1),
	@inServer 		AS CHAR(1),
	@oppRecID 	            	AS INTEGER OUTPUT


)
AS

set @oppRecID=0

IF @inAkcija = 'New'
   BEGIN
	INSERT INTO  SlogKalk (Stanica, OtpUprava, OtpStanica, OtpBroj, OtpDatum, ObrGodina, ObrMesec,
			ZsUlPrelaz, UlEtiketa, DatumUlaza, ZsIzPrelaz, IzEtiketa, DatumIzlaza, PrUprava, PrStanica, PrBroj, PrDatum,
			BrojVoza, SatVoza, Najava, NajavaKola, Najava2, NajavaKola2, ObrGodina2, ObrMesec2, SifraTarife, Ugovor, Posiljalac, PlatilacFRR, Primalac,  PlatilacNFR, VrPos, Prevoz, Saobracaj, VrSao, VrPrevoza, UkupnoKola, PrevozniPutZs,
			TkmZS, SkmZS, SifraIzjave, FrRacun, K115_e, K115_d,  FrankoPoCIM_e, FrankoPoCIM_d, FrNaknade, FrDoPrelaza, Incoterms, IsporukaVal, Isporuka, PouzeceVal, Pouzece, VrednostRobeVal, VrednostRobe,
			tlValuta, tlSumaFr, tlSumaUp, tlSumaFrDin, tlSumaUpDin, tlPrevFr, tlPrevUp, tlNakFr, tlNakUp, tlPrevFrDin, tlPrevUpDin, tlNakFrDin, tlNakUpDin, tlNakCo82, tlNakCo, rSumaFr, rSumaUp, rSumaFrDin, rSumaUpDin, rK115_d, SifraK211, Referent1, DatumObrade,
			CarStanica, CarPrimalacPIB, CarPrimalacNaziv, CarPrimalacSediste, CarPrimalacZemlja, CarValuta, CarFaktura, CarBrojFakture, CarDokumenti, CarKnjiga,
			CarDatum, CarAgent, CarXml, Server)
	VALUES ( @inStanicaUnosa, @inOtpUprava , @inOtpStanica , @inOtpBroj, @inOtpDatum , @inObrGodina, @inObrMesec, @inZsUlPrelaz, @inUlEtiketa, @inDatumUlaza,
			@inZsIzPrelaz, @inIzEtiketa, @inDatumIzlaza, @inPrUprava, @inPrStanica, @inPrBroj, @inPrDatum, @inBrojVoza, @inSatVoza, @inNajava,@inNajavaKola, @inNajava2, @inNajavaKola2, @inObrGodina, @inObrMesec,
			@inSifraTarife, @inUgovor, @inPosiljalac, @inPlatilacFRR, @inPrimalac, @inPlatilacNFR, @inVrPos, @inPrevoz, @inSaobracaj, @inVrSao,@inVrPrevoza,@inUKK, @inZsPrevozniPut, @intkm,
			@inskm, @inIzjava, @inFrRacun, @inK115_e, @inK115_d, @inFrankoPoCIM_e, @inFrankoPoCIM_d, @inFrNaknade, @inFrDoPrelaza, @inIncoterms, @inIsporukaVal, @inIsporuka, @inPouzeceVal, @inPouzece, @inVrednostRobeVal, @inVrednostRobe,
			@inTLValuta, @inTLSumaFr, @inTLSumaUp, @inTLSumaFrDin, @inTLSumaUpDin, @inTLPrevFr, @inTLPrevUp, @inTLNakFr, @inTLNakUp, @inTLPrevFrDin, @inTLPrevUpDin, @inTLNakFrDin, 
			@inTLNakUpDin, @inTLNakCo82, @inTLNakCo, @inrSumaFr, @inrSumaUp, @inrSumaFrDin, @inrSumaUpDin, @inrK115_d, @inSifraK211, @inReferent1, @inObradaDatum, @inCarStanica, @inCarPrimalacPIB, @inCarPrimalacNaziv, @inCarPrimalacSediste,
			@inCarPrimalacZemlja, @inCarValuta, @inCarFaktura, @inCarBrFakture, @inCarDokumenti, @inCarKnjiga, @inCarDatum, @inCarAgent, @inCarXml, @inServer)

	set @oppRecID=@@IDENTITY

   END
ELSE IF @inAkcija = 'Del'
    BEGIN
	 DELETE FROM SlogKalk  WHERE OtpUprava=@inOtpUprava and OtpStanica=@inOtpStanica and OtpBroj=@inOtpBroj and OtpDatum=@inOtpDatum
    END
ELSE IF @inAkcija = 'Upd'
    BEGIN
    Update SlogKalk
     SET  

	OtpUprava		= @inOtpUprava,
	OtpStanica		= @inOtpStanica,
	OtpBroj			= @inOtpBroj,
	OtpDatum        		= @inOtpDatum,
	ObrGodina       		= @inObrGodina,
	ObrMesec        		= @inObrMesec,
	ZsUlPrelaz      		= @inZsUlPrelaz,
	UlEtiketa       		= @inUlEtiketa,
	DatumUlaza      		= @inDatumUlaza,
	ZsIzPrelaz		= @inZsIzPrelaz,
	IzEtiketa       		= @inIzEtiketa,
	DatumIzlaza     		= @inDatumIzlaza,
	PrUprava        		= @inPrUprava,
	PrStanica       		= @inPrStanica,
	PrBroj          		= @inPrBroj,
	PrDatum         		= @inPrDatum,
	BrojVoza        		= @inBrojVoza,
	SatVoza         		= @inSatVoza,
	Najava          		= @inNajava,
	NajavaKola      		= @inNajavaKola,
	Najava2          		= @inNajava2,
	NajavaKola2      		= @inNajavaKola2,
	ObrGodina2       		= @inObrGodina,
	ObrMesec2        		= @inObrMesec,
	SifraTarife     		= @inSifraTarife,
	Ugovor          		= @inUgovor,
	Posiljalac      		= @inPosiljalac,
	PlatilacFRR     		= @inPlatilacFRR,
	Primalac        		= @inPrimalac,
	PlatilacNFR     		= @inPlatilacNFR,
	VrPos           		= @inVrPos,
	Prevoz          		= @inPrevoz,
	Saobracaj       		= @inSaobracaj,
	VrSao           		= @inVrSao,
	VrPrevoza       		= @inVrPrevoza,
	UkupnoKola    		= @inUKK,
	PrevozniPutZs		= @inZsPrevozniPut,
	TkmZS             		= @intkm,
	SkmZS             		= @inskm,
	SifraIzjave       		= @inIzjava,
	FrRacun         		= @inFrRacun,
	K115_e			= @inK115_e, 
	K115_d			= @inK115_d,  
	FrankoPoCIM_e		= @inFrankoPoCIM_e, 
	FrankoPoCIM_d		= @inFrankoPoCIM_d,
	FrNaknade       		= @inFrNaknade,
	FrDoPrelaza     		= @inFrDoPrelaza,
	Incoterms       		= @inIncoterms,
	IsporukaVal     		= @inIsporukaVal,
	Isporuka        		= @inIsporuka,
	PouzeceVal      		= @inPouzeceVal,
	Pouzece         		= @inPouzece,
	VrednostRobeVal 	= @inVrednostRobeVal,
	VrednostRobe    	= @inVrednostRobe,
	TLValuta        		= @inTLValuta,
	TLSumaFR   		= @inTLSumaFR,
	TLSumaUP  		= @inTLSumaUP,
	TLSumaFRDin   		= @inTLSumaFRDin,
	TLSumaUPDin  		= @inTLSumaUPDin,
	TLPrevFR        		= @inTLPrevFR,
	TLPrevUP        		= @inTLPrevUP,
	TLNakFR         		= @inTLNakFR,
	TLNakUP         		= @inTLNakUP,
	TLPrevFRDin    		= @inTLPrevFR,
	TLPrevUPDin   		= @inTLPrevUP,
	TLNakFRDin     		= @inTLNakFR,
	TLNakUPDin     		= @inTLNakUP,
	TLNakCo82       		= @inTLNakCo82,
	TLNakCo       		= @inTLNakCo,
	rSumaFR		= @inrSumaFR,
	rSumaUP		= @inrSumaUP,
	rSumaFRDin		= @inrSumaFRDin,
	rSumaUPDin		= @inrSumaUPDin,
	rK115_d		= @inrK115_d,
	SifraK211		= @inSifraK211,
	Referent1       		= @inReferent1,
	DatumObrade     	= @inObradaDatum

   	 WHERE OtpUprava=@inOtpUprava and OtpStanica=@inOtpStanica and OtpBroj=@inOtpBroj and OtpDatum=@inOtpDatum

	SELECT @oppRecID= RecID From SlogKalk 
	WHERE OtpUprava=@inOtpUprava and OtpStanica=@inOtpStanica and OtpBroj=@inOtpBroj and OtpDatum=@inOtpDatum
	
    END
RETURN @@RowCount
GO
